backend:
  name: git-gateway
  repo: playec/playec.github.io
  branch: main
  base_url: "https://playec.github.io"

site_url: https://playec.netlify.app

media_folder: "public/uploads"
public_folder: "/uploads"

scripts:
  - https://cdn.jsdelivr.net/npm/uuid@latest/dist/umd/uuidv4.min.js

media_library:
  name: uploadcare
  config:
    publicKey: demopublickey
collections:
  - name: "menus"
    label: "Menus"
    widget: "object"
    label_singular: "Menu"
    folder: "src/menus"
    extension: "json"
    format: "json"
    slug: '{{slug}}'
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string", tagname: "h1" }
      - { label: "Slug", name: "slug", widget: "string", hint: "menu-slug", default: 'menu-slug' }
      - label: "Body"
        name: "body"
        collapsed: true
        widget: "list"
        fields:
          - { label: "Order", name: "order", widget: "number", value_type: "int", min: 0, max: 100 }
          - { label: "Title", name: "title", widget: "string", tagname: "h1" }
          - { label: "Slug", name: "slug", widget: "string" }
          - { label: "Target", name: "target", widget: "string", required: false }
  - name: "items"
    label: "Items"
    widget: "object"
    label_singular: 'Item'
    folder: "src/items"
    extension: "json"
    format: "json"
    slug: '{{slug}}'
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string", tagname: "h1" }
      - { label: "Categories", name: "categories", widget: "list", default: [] }
      - { label: "Tags", name: "tags", widget: "list", default: [] }
      - { label: "Slug", name: "slug", widget: "string", hint: "item-title-one", default: 'item-title' }
      - {
          label: "Featured Image",
          name: "thumbnail",
          widget: "image",
          choose_url: true,
          default: "/uploads/playstation.png"
        }
      - {
          label: "Publish Date",
          name: "date",
          widget: "datetime",
          format: "",
          default: "YYYY-MM-DD HH:mm"
        }
      - { label: "Content", name: "content", widget: "text", hint: "Información del producto." }
      - label: "Cards"
        name: "cards"
        collapsed: true
        widget: "list"
        fields:
          - {label: "Detail", name: "detail", widget: "string", required: false}
          - {label: "Value", name: "value", widget: "number", value_type: "int", default: 5, min: 1, max: 100}
          - {label: "Price", name: "price", widget: "number", value_type: "float", default: 0.00, min: 0.00}
  - name: "pages"
    label: "Pages"
    widget: "object"
    label_singular: "Page"
    folder: "src/pages"
    extension: "json"
    format: "json"
    slug: '{{slug}}'
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string", tagname: "h1" }
      - { label: "Slug", name: "slug", widget: "string", default: 'page-path' }
      - {
          label: "Featured Image",
          name: "thumbnail",
          widget: "image",
          choose_url: true,
          required: false
        }
      - { label: "Body", name: "body", widget: "text" }
          
          