backend:
  name: git-gateway
  repo: playec/playec.github.io
  branch: main
  base_url: "https://playec.github.io"

site_url: https://playec.netlify.app

media_folder: "public/uploads"
public_folder: "/uploads"

scripts:
  - https://cdn.jsdelivr.net/npm/uuid@latest/dist/umd/uuidv4.min.js

media_library:
  name: uploadcare
  config:
    publicKey: demopublickey
collections:
  - name: "posts"
    label: "Posts"
    widget: "object"
    label_singular: 'Post'
    folder: "src/posts"
    extension: "json"
    format: "json"
    slug: '{{slug}}'
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string", tagname: "h1" }
      - { label: "Tags", name: "tags", widget: "list", default: ["Tarjeta"] }
      - { label: "Slug", name: "slug", widget: "string", hint: "post-title-one", default: 'post-title' }
      - {
          label: "Featured Image",
          name: "thumbnail",
          widget: "image",
          choose_url: true,
          default: "/uploads/playstation.png"
        }
      - {
          label: "Publish Date",
          name: "date",
          widget: "datetime",
          format: "",
          default: "YYYY-MM-DD HH:mm"
        }
      - { label: "Content", name: "content", widget: "text", hint: "Información del producto." }
      - label: "Cards"
        name: "cards"
        collapsed: true
        widget: "list"
        fields:
          - {label: "Value", name: "value", widget: "number", value_type: "int", default: 5, min: 1, max: 100}
          - {label: "Price", name: "price", widget: "number", value_type: "float", default: 0.00, min: 0.00}
          
          